version: '3'
services:
  my-app:
    image: 211899496878.dkr.ecr.us-east-2.amazonaws.com/my-app:1.0
    ports:
      - 3000:3000
  mongodb:
    image: mongo #image name
    ports:
      - 27017:27017 #linking ports
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin #authorization details
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db # storage or db
  mongo-express:
    image: mongo-express
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo-data:
    driver: local
