---
- name: Create AWS EC2 Instance
  hosts: local
  connection: local
  gather_facts: false
  vars:
    keypair: key_june13
    instance_type: t2.micro
    image: ami-0d8d212151031f51c
    region: us-east-2
    count: 4
    security_group: Ansible-SecurityGroup
    aws_access_key: <ACTUAL AWS_ACCESS_KEY>
    aws_secret_key: <ACTUAL AWS_SECRET_KEY>

  tasks:
    - name: Create a security group with Port 22, 80 and 443 open to 0.0.0.0/0
      ec2_group:
        name: '{{ security_group }}'
        description: Security Group for Servers with 22, 80, 443
        region: '{{ region }}'
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
        aws_access_key: '{{ aws_access_key }}'
        aws_secret_key: '{{ aws_secret_key }}'

    - name: Create New AWS EC2 Server
      ec2:
        key_name: '{{ keypair }}'
        instance_type: '{{ instance_type }}'
        image: '{{ image }}'
        group: '{{ security_group }}'
        region: '{{ region }}'
        instance_tags:
          Name: Vadym-Ansible-Deployment
          Type: AnsibleEC2-byVadym
        count: ' {{ count  }}'
        wait: true
        aws_access_key: '{{ aws_access_key }}'
        aws_secret_key: '{{ aws_secret_key }}'
      register: ec2

    - name: Print all ec2 variables
      debug: var=ec2
