---
- name: Install Apache and Upload my web page
  hosts: all # all EC2s
  become: yes # root user

  vars:
    source_file: ./website/index.html
    destin_file: /var/www/html

  tasks:
    - name: Check and print Linux Version
      debug: var=ansible_os_family

    - block: # ========= RedHat BLOCK =========
        - name: Install Apache Web Server for RedHat
          yum: name=httpd state=latest

        - name: Copy website to servers for RedHat
          copy: src={{ source_file }} dest={{ destin_file }} mode=0555
          notify: Restart Apache RedHat # on file change notify handlers

        - name: Start website and enable on boot for RedHat
          service: name=httpd state=started enabled=yes

      when: ansible_os_family == "RedHat"

    - block: # ========= Debian BLOCK =========
        - name: Install Apache Web Server for RedHat
          apt: name=apache2 state=latest

        - name: Copy website to servers for RedHat
          copy: src={{ source_file }} dest={{ destin_file }} mode=0555
          notify: Restart Apache Debian # on file change notify handlers

        - name: Start website and enable on boot for RedHat
          service: name=apache2 state=started enabled=yes

      when: ansible_os_family == "Debian"

  handlers: # restart server on notification
    - name: Restart Apache for RedHat
      service: name=httpd state=restarted

    - name: Restart Apache for Debian
      service: name=apache2 state=restarted
